import { locates } from '@plugin'

export const zhCN = {
  send: '发送',
  add: '添加',
  chat: '聊天',
  setting: '设置',
  newBot: '创建新的Bot',
  ctrl: '控制',
  selectAccount: '账户',
  create: '创建',
  connect: '连接',
  deleting: '删除中...',
  dead: '你死亡了.',
  connected: '成功连接.',
  confirmDelete: '确认删除该Bot?',
  disconnect: '断开连接',
  autoReconnectMsg: '将在五秒后自动重新连接!',
  recoring: '录制中...',
  stopRecording: '录制结束!',

  save: '保存配置',
  enableCommand: '启用命令系统',
  hostname: '服务器地址',
  port: '端口',
  version: '服务器版本',
  autoReconnect: '自动重连',
  shakeHand: '摇手臂',
  commandPrefix: '命令前缀',
  autoRespawn: '自动重生',

  removeItems: '不录制掉落物',
  removeExperienceOrb: '不录制经验球',
  removeBats: '不录制蝙蝠',
  removePhantoms: '不录制幻翼',
  noWeather: '没有天气变化',
  dayTime: '录制游戏时间',
  withPlayerOnly: '玩家在身边才录制',
  checkTime: '检查时间间隔',
  splitTime: '分段录制时长',
  autoRecording: '自动开始录制',

  stop: '停止任务',
  jump: '跳跃',
  respawn: '重生',
  swap: '交换双手物品',
  getOn: '上矿车/船',
  getOff: '下矿车/船',
  drop: '丢弃物品',
  keepWalk: '持续行走',
  useItem: '使用物品',
  keepUseItem: '持续使用物品',
  attack: '攻击怪物',
  keepAttack: '持续攻击',
  dig: '破坏方块',
  keepDig: '持续破坏方块',
  place: '放置方块',
  keepPlace: '持续放置方块',
  recording: '开始/停止录制'
}

export default locates<typeof zhCN>({
  'zh-cn': zhCN,
  'en-us': {
    send: 'Send',
    add: 'Add',
    chat: 'Chat',
    setting: 'Setting',
    ctrl: 'Ctrl',
    newBot: 'Create New Bot',
    selectAccount: 'Select Account',
    create: 'CREATE',
    connect: 'CONNECT',
    deleting: 'Deleting...',
    dead: 'You are dead.',
    connected: 'Connected.',
    disconnect: 'Disconnect',
    autoReconnectMsg: 'Will automatically reconnect in five seconds!',
    confirmDelete: 'Are you sure to delete the BOT?',
    recoring: 'Recording...',
    stopRecording: 'Stop recording!',

    save: 'Save',
    enableCommand: 'ENABLE COMMAND',
    hostname: 'HOSTNAME',
    port: 'PORT',
    version: 'VERSION',
    autoReconnect: 'AUTO RECONNECT',
    shakeHand: 'SHAKE HAND',
    commandPrefix: 'COMMAND PREFIX',
    autoRespawn: 'AUTO RESPAWN',

    removeItems: 'REMOVE ITEMS',
    removeExperienceOrb: 'REMOVE EXPERIENCE ORB',
    removeBats: 'REMOVE BATS',
    removePhantoms: 'REMOVE PHANTOMS',
    noWeather: 'NO WEATHER',
    dayTime: 'DAY TIME',
    withPlayerOnly: 'WITH PLAYER ONLY',
    checkTime: 'CHEKC TIME',
    splitTime: 'SPLIT TIME',
    autoRecording: 'AUTO RECORDING',

    stop: 'STOP',
    jump: 'JUMP',
    respawn: 'RESPAWN',
    swap: 'SWAP',
    getOn: 'GET ON',
    getOff: 'GET OFF',
    drop: 'DROP',
    keepWalk: 'KEEP WALK',
    useItem: 'USE ITEM',
    keepUseItem: 'KEEP USE ITEM',
    attack: 'ATTACK',
    keepAttack: 'KEEP ATTACK',
    dig: 'DIG',
    keepDig: 'KEEP DIG',
    place: 'PLACE',
    keepPlace: 'KEEP PLACE',
    recording: 'RECORDING'
  }
})
